[project]
name = "mcpclient"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.4.8",
    "openai>=1.78.1",
    "python-dotenv>=1.1.0",
    "textual>=3.2.0",
    "transformers>=4.51.3",
]
